"""添加 merge_tasks 表

Revision ID: 002
Revises: 001
Create Date: 2026-05-25

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False, comment='任务ID'),
    sa.Column('task_type', sa.String(length=20), nullable=False, comment='任务类型: audio_replace/bgm/mix'),
    sa.Column('video_id', sa.BigInteger(), nullable=False, comment='视频资产ID'),
    sa.Column('params', sa.Text(), nullable=False, comment='任务参数JSON'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued/processing/completed/failed/cancelled'),
    sa.Column('result', sa.Text(), nullable=True, comment='任务结果JSON'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merge_tasks')
    # ### end Alembic commands ###
