"""添加 pipeline_executions 表

Revision ID: 009
Revises: 008
Create Date: 2026-05-31

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_executions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('execution_id', sa.String(length=64), nullable=False, comment='执行ID，全局唯一'),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False, comment='流水线名称'),
    sa.Column('pipeline_type', sa.String(length=50), nullable=False, comment='流水线类型：video/product/video_overall'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='执行状态'),
    sa.Column('current_processor_index', sa.Integer(), nullable=False, comment='当前执行到的处理器索引'),
    sa.Column('total_processors', sa.Integer(), nullable=False, comment='总处理器数量'),
    sa.Column('input_params', sa.JSON(), nullable=False, comment='初始输入参数'),
    sa.Column('context_data', sa.JSON(), nullable=True, comment='上下文数据快照'),
    sa.Column('context_metadata', sa.JSON(), nullable=True, comment='上下文元数据快照'),
    sa.Column('errors', sa.JSON(), nullable=True, comment='错误信息列表'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='最后一次错误信息'),
    sa.Column('result', sa.JSON(), nullable=True, comment='最终执行结果'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_executions')
    # ### end Alembic commands ###
