"""添加商品解析相关字段

Revision ID: 011
Revises: 010
Create Date: 2026-05-31

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011'
down_revision: Union[str, None] = '010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('parsing_status', sa.String(length=20), nullable=True, comment='解析状态：pending/running/completed/failed'))
    op.add_column('products', sa.Column('execution_id', sa.String(length=64), nullable=True, comment='流水线执行ID，用于断点续跑'))
    op.add_column('products', sa.Column('parsing_error', sa.Text(), nullable=True, comment='解析错误信息'))
    op.add_column('products', sa.Column('ai_features', sa.JSON(), nullable=True, comment='AI解析结果特征'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ai_features')
    op.drop_column('products', 'parsing_error')
    op.drop_column('products', 'execution_id')
    op.drop_column('products', 'parsing_status')
    # ### end Alembic commands ###
