-- 创建内部视频素材库表
CREATE TABLE IF NOT EXISTS video_library (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    title VARCHAR(200) NULL COMMENT '视频标题',
    description TEXT NULL COMMENT '视频描述',
    url VARCHAR(500) NOT NULL COMMENT '视频存储URL',
    cover_url VARCHAR(500) NULL COMMENT '封面图URL',
    file_size BIGINT NULL COMMENT '文件大小(字节)',
    duration INT NULL COMMENT '视频时长(秒)',
    format VARCHAR(20) NULL COMMENT '文件格式',
    source_type INT NOT NULL DEFAULT 0 COMMENT '来源：0-内部上传, 1-爆款抓取, 2-人工录入, 3-其他',
    hot_score INT NULL COMMENT '爆款分数(0-100)',
    category VARCHAR(100) NULL COMMENT '视频分类/商品品类',
    tags JSON NULL COMMENT '视频标签数组',
    parsed_data JSON NULL COMMENT '结构化解析数据',
    parsing_status VARCHAR(20) NULL DEFAULT 'pending' COMMENT '解析状态：pending/running/completed/failed',
    execution_id VARCHAR(64) NULL COMMENT '流水线执行ID，用于断点续跑',
    parsing_error TEXT NULL COMMENT '解析错误信息',
    created_by BIGINT NOT NULL COMMENT '创建人ID(管理员ID)',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_category (category),
    INDEX idx_hot_score (hot_score),
    INDEX idx_source_type (source_type),
    INDEX idx_created_at (created_at),
    UNIQUE KEY uk_url (url)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内部视频素材库表';
